version: 2.1
orbs:
  node: circleci/node@0.0.9

jobs:
  build:
    executor:
      name: node/node
      tag: "latest"
    working_directory: ~/repo

    steps:
      - checkout
      - node/with-cache:
          dir: ~/repo/node_modules
          cache-version: v1
          steps:
            - run: npm install
            - run:
                name: test
                command: |
                  sudo npm install -g mocha
                  npm run test
workflows:
  version: 2
  build:
    jobs:
      - build
